### ISSUE TITLE
Future of this library

### ISSUE THREAD

**Issue by timjacobi** [fjl/go-couchdb#12]
Hi Felix. I'm curious how you envisage the future of this library. There are a couple of golang Couch DB clients on Github but this one has the most stars and probably the best code too. 

Unfortunately there are some good open pull requests against this library that are not taken care off. Also it seems like there wasn't any other activity in this repo for about 2 years. 

I have forked this repo and have incorporated most of the pull requests. I'm happy to continue to maintain the code but would need to know what your take on it is as we would need to figure out how we want to handle it going forward.

Cheers
Tim

**Comment by flimzy** [comment]
Knowing the future of this library would be really good. I've often wondered the same.

But without a published license, I'm afraid to fork it myself.

**Comment by fjl** [comment]
Damn, I totally forgot about this repo! I built this for my previous job and then joined Ethereum, which took up all my time and interest. Will update it now!

**Comment by fjl** [comment]
Updates pushed!
