### ISSUE TITLE
Sequence IDs are no longer integers

### ISSUE THREAD

**Issue by flimzy** [fjl/go-couchdb#14]
As of CouchDB 2.0, Sequence IDs are no longer integers, and [can be any valid JSON object](http://docs.couchdb.org/en/2.0.0/whatsnew/2.0.html#upgrade-notes).  As far as I know, the only place this is exposed in this library is in the ChangesFeed.  I suggest changing the SeqID to a `json.RawMessage` type to accommodate this change.

Another option might be to expose the raw Seq value as a separate field (and set Seq to 0 when it's not an integer).  This would allow CouchDB 1.6 users to continue using this library with no changes.

**Comment by tomkcook** [comment]
Yes, this is a problem for us too.  The DB changes feed does not work on couchdb 2.x.

**Comment by flimzy** [comment]
@tomkcool Since I reported this about 2 years ago, and never got a response, I implemented a new CouchDB driver on my own, which resolves this issue, along with some other improvements. Maybe it can help you, too. You can find it at github.com/go-kivik/kivik

**Comment by tomkcook** [comment]
Thanks, but I am supporting a substantial amount of code written around this package.

@fjl is there any chance at all of getting this merged please?

**Comment by fjl** [comment]
Fixed in https://github.com/fjl/go-couchdb/commit/d69df27bdd709700f6e19f1249d1f9befc32f223
