### ISSUE TITLE
couchapp does not parse _id

### ISSUE THREAD

**Issue by dravenk** [fjl/go-couchdb#19]
<img width="1496" alt="ffff" src="https://user-images.githubusercontent.com/14295318/44183923-a6e77b80-a13f-11e8-95a4-ef325453935a.png">

**Comment by fjl** [comment]
This is by design: if you pass a `nil` value for the `ignores` parameter, it will use the `DefaultIgnorePatterns`. The default behavior is excluding CouchDB system fields starting with `_`.
