### ISSUE TITLE
JSON decoding failure

### ISSUE THREAD

**Issue by tomkcook** [fjl/go-couchdb#23]
I haven't had time to look into the cause of this, but the following fails silently:

```
package main

import (
        "fmt"
        "log"
        couch "vsys/go-couchdb"
)

func main() {
        server, err := couch.NewClient("http://127.0.0.1:5984/", nil)
        if err != nil {
                log.Fatalf("Error creating client: %v", err)
        }
        db := server.DB("my_db")
        allDocs := struct {
                Offset int `json:"offset"`
                Rows   []struct {
                        Id    string `json:"id"`
                        Key   string `json:"key"`
                        Value struct {
                                Rev string `json:"rev"`
                        } `json:"rows"`
                }
                TotalRows int `json:"total_rows"`
        }{}

        err = db.AllDocs(&allDocs, nil)
        if err != nil {
                log.Fatalf("Failed to get document list: %v", err)
        }
        fmt.Printf("Got document list with %d rows\n", len(allDocs.Rows))
}
```

The tag `json:"rows"\` is on the wrong line; `Value` should be tagged as the JSON name `value` and `Rows` should be tagged as `rows`.  Despite this, everything except the `Rev` field is decoded correctly.

**Comment by fjl** [comment]
I think this might be a general issue with encoding/json. The default behavior of the Go JSON package is to decode into struct fields of the same name. It does not warn if a field in the JSON input is missing, or if there are extra fields, so if your struct definition doesn't match the input, you may get silent failures.
