### ISSUE TITLE
Design documents improperly escaped

### ISSUE THREAD

**Issue by flimzy** [fjl/go-couchdb#6]
While trying to query a view, I discovered that design documents are improperly escaped.

The first indication of a problem was that go-couchdb was complaining of insufficient permissions to access the view:

> GET http://xxx.xxx.xxx/_users/_design/users/_view/by_provider: (403) forbidden: Only admins can access design document actions for system databases.

And my couch log showed these requests:

> [Tue, 01 Sep 2015 22:54:29 GMT] [info] [<0.268.0>] xxx.xxx.xxx.xxx - - GET /_users/_design%2Fusers/_view/by_provider 301
> [Tue, 01 Sep 2015 22:54:30 GMT] [info] [<0.269.0>] xxx.xxx.xxx.xxx  - - GET /_users/_design/users/_view/by_provider 403

So it turns out the redirect wasn't getting the necessary auth headers.  But the _real_ problem here is that the slash in `_design/users` shouldn't be escaped at all.

I have a PR coming soon.

**Comment by fjl** [comment]
Fixed in 9bc16a45318b1103f4938079b9725703404fb976
